### ISSUE TITLE
Make tooltips box fit the text

### ISSUE THREAD

**Issue by Alan-FGR** [Alan-FGR/Engines#4]
when text is too short the tooltips span won't shrink to fit and it looks terrible:
![image](https://user-images.githubusercontent.com/8399299/34427932-88119cc0-ec2e-11e7-83d1-6fe1f481671a.png)
gonna need help here

**Comment by Alan-FGR** [comment]
tried setting span to inline-block and wrapping it in a div w/o width, no deal :(

**Comment by Alan-FGR** [comment]
```CSS
div.tooltip {
    position: relative;
    border: 2px dotted black !important;
}

.tooltip .tooltiptext {
    visibility: hidden;
    width: 10em;
    background-color: #000;
    color: #fff;
    padding: 0.8em 0.4em;
    position: absolute;
    z-index: 1;
    top: 1em;
    left: 0;
}

.tooltip:hover .tooltiptext {
    visibility: visible;
}
```
```HTML
<div class="tooltip " style="background-color:#bf9"> Very Good
    <span class="tooltiptext">Win / Mac / Lin / iOS / And / Rpi</span>
</div>
```
